#
# Makefile for the vibrator driver ICs with vibrator driver
#
obj-$(CONFIG_MSM_VIBRATOR) += msm_vibrator.o
# Makefile for Vibrator controlled by SUB PMIC Regulator.
obj-$(CONFIG_SM5703_VIBRATOR) += sm5703_vibrator.o

#
#  makefile for motor driver kernel module
#

obj-$(CONFIG_STEP_MOTOR_STSPIN220)        += stspin220_step_motor.o
obj-$(CONFIG_SS_VIBRATOR)		+= ss_vibrator.o

